################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
[de]
languageName = "De"
languageCode = "de-at"
contentDir = "content/deutsch"
weight = 2
